export interface SlackScriptImage {
  filename: string;
  mimeType: string;
  base64: string;
}

export function generateSlackBrowserScript(images: SlackScriptImage[]): string {
  const serializedImages = JSON.stringify(images);

  return `// Generated by Emoji Explorer. Paste into DevTools while signed in at
// https://YOUR-WORKSPACE.slack.com/customize/emoji
(async () => {
  const images = ${serializedImages};
  const sleep = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
  const token = [
    document.querySelector('input[name="token"]')?.value,
    globalThis.TS?.boot_data?.api_token,
    globalThis.boot_data?.api_token,
    globalThis.slackDebug?.token,
  ].find((value) => typeof value === 'string' && value.length > 0);

  if (!location.hostname.endsWith('.slack.com')) {
    throw new Error('Run this script on your Slack workspace customize/emoji page.');
  }
  if (!token) {
    throw new Error('Could not find the Slack page token. Open /customize/emoji and retry.');
  }

  const emojiName = (filename) => filename
    .replace(/\\.[^.]+$/, '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^[_-]+|[_-]+$/g, '');

  const decodeImage = (image) => {
    const bytes = Uint8Array.from(atob(image.base64), (character) => character.charCodeAt(0));
    return new File([bytes], image.filename, { type: image.mimeType });
  };

  const report = [];
  for (const [index, image] of images.entries()) {
    const name = emojiName(image.filename);
    const progress = '[' + (index + 1) + '/' + images.length + ']';
    try {
      const form = new FormData();
      form.append('token', token);
      form.append('name', name);
      form.append('mode', 'data');
      form.append('image', decodeImage(image));
      form.append('_x_reason', 'customize-emoji-add');
      form.append('_x_mode', 'online');

      const response = await fetch('/api/emoji.add', {
        method: 'POST',
        credentials: 'same-origin',
        body: form,
      });
      const body = await response.json().catch(() => ({}));
      if (!response.ok || body.ok === false) {
        throw new Error(body.error || 'HTTP ' + response.status);
      }
      report.push({ filename: image.filename, name, status: 'uploaded' });
      console.log('[slack-emoji-upload]', progress, 'uploaded:', name);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      report.push({ filename: image.filename, name, status: 'error', error: message });
      console.error('[slack-emoji-upload]', progress, 'failed:', name, message);
    }
    if (index < images.length - 1) await sleep(1000);
  }

  globalThis.slackEmojiUploadReport = report;
  console.table(report);
  return report;
})();`;
}

/** Compress data only: uploader code remains readable, with no eval or CDN loader. */
export async function generateCompactSlackBrowserScript(images: SlackScriptImage[]): Promise<string> {
  const plain = generateSlackBrowserScript(images);
  if (typeof CompressionStream === "undefined") return plain;
  const json = JSON.stringify(images);
  const stream = new Blob([json]).stream().pipeThrough(new CompressionStream("gzip"));
  const bytes = new Uint8Array(await new Response(stream).arrayBuffer());
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000));
  }
  const decode = `JSON.parse(await new Response(new Blob([Uint8Array.from(atob(${JSON.stringify(btoa(binary))}), c => c.charCodeAt(0))]).stream().pipeThrough(new DecompressionStream('gzip'))).text())`;
  const compact = plain.replace(`const images = ${json};`, `const images = ${decode};`);
  return new Blob([compact]).size < new Blob([plain]).size ? compact : plain;
}
