import replacementRuntime from './slackReplacementRuntime.js?raw';
import {planSlackEmojiReplacements} from './slackEmojiReplacements';

export interface SlackScriptImage {
  filename: string;
  mimeType: string;
  base64: string;
}

export function generateSlackBrowserScript(images: SlackScriptImage[], options: {replaceSmaller?: boolean} = {}): string {
  const serializedImages = JSON.stringify(images);

  return `// Generated by Emoji Explorer. Paste into DevTools while signed in at
// https://YOUR-WORKSPACE.slack.com/customize/emoji
(async () => {
  const images = ${serializedImages};
  const sleep = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
  const token = [
    document.querySelector('input[name="token"]')?.value,
    globalThis.TS?.boot_data?.api_token,
    globalThis.boot_data?.api_token,
    globalThis.slackDebug?.token,
  ].find((value) => typeof value === 'string' && value.length > 0);

  if (!location.hostname.endsWith('.slack.com')) {
    throw new Error('Run this script on your Slack workspace customize/emoji page.');
  }
  if (!token) {
    throw new Error('Could not find the Slack page token. Open /customize/emoji and retry.');
  }

  const emojiName = (filename) => filename
    .replace(/\\.[^.]+$/, '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^[_-]+|[_-]+$/g, '');

  const decodeImage = (image) => {
    const bytes = Uint8Array.from(atob(image.base64), (character) => character.charCodeAt(0));
    return new File([bytes], image.filename, { type: image.mimeType });
  };

  ${options.replaceSmaller ? replacementRuntime + "\nreturn await runSlackEmojiReplacement(images, token, " + planSlackEmojiReplacements.toString() + ");" : ""}

  const report = [];
  for (const [index, image] of images.entries()) {
    const name = emojiName(image.filename);
    const progress = '[' + (index + 1) + '/' + images.length + ']';
    try {
      const form = new FormData();
      form.append('token', token);
      form.append('name', name);
      form.append('mode', 'data');
      form.append('image', decodeImage(image));
      form.append('_x_reason', 'customize-emoji-add');
      form.append('_x_mode', 'online');

      const response = await fetch('/api/emoji.add', {
        method: 'POST',
        credentials: 'same-origin',
        body: form,
      });
      const body = await response.json().catch(() => ({}));
      if (!response.ok || body.ok === false) {
        throw new Error(body.error || 'HTTP ' + response.status);
      }
      report.push({ filename: image.filename, name, status: 'uploaded' });
      console.log('[slack-emoji-upload]', progress, 'uploaded:', name);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      report.push({ filename: image.filename, name, status: 'error', error: message });
      console.error('[slack-emoji-upload]', progress, 'failed:', name, message);
    }
    if (index < images.length - 1) await sleep(1000);
  }

  globalThis.slackEmojiUploadReport = report;
  console.table(report);
  return report;
})();`;
}

/** Compress data only: uploader code remains readable, with no eval or CDN loader. */
export async function generateCompactSlackBrowserScript(images: SlackScriptImage[], options: {replaceSmaller?: boolean} = {}): Promise<string> {
  const plain = generateSlackBrowserScript(images, options);
  if (typeof CompressionStream === "undefined") return plain;
  const json = JSON.stringify(images);
  const stream = new Blob([json]).stream().pipeThrough(new CompressionStream("gzip"));
  const bytes = new Uint8Array(await new Response(stream).arrayBuffer());
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + 0x8000));
  }
  const decode = slackPayloadDecoder(btoa(binary));
  const compact = plain.replace(`const images = ${json};`, `const images = ${decode};`);
  return new Blob([compact]).size < new Blob([plain]).size ? compact : plain;
}

/** Shared by browser exports and the dependency-free ZIP generator. */
export function slackPayloadDecoder(encoded: string): string {
  // Yield between bounded chunks: Array.from over the full payload creates a
  // multi-second main-thread task for a complete catalog in Slack's browser.
  return `await (async () => {
    console.log('[slack-emoji-upload] Preparing images… Please keep this page open.');
    const encoded = ${JSON.stringify(encoded)};
    const chunks = [];
    for (let offset = 0; offset < encoded.length; offset += 65536) {
      const binary = atob(encoded.slice(offset, offset + 65536));
      const bytes = new Uint8Array(binary.length);
      for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
      chunks.push(bytes);
      await new Promise(resolve => setTimeout(resolve, 0));
    }
    return JSON.parse(await new Response(new Blob(chunks).stream().pipeThrough(new DecompressionStream('gzip'))).text());
  })()`;
}
